---
title: "Top_GO_Dalia_version"
output: pdf_document
editor_options: 
  chunk_output_type: console
---
# Environment
```{r}
library(tidyverse)
library(janitor)
library(biomaRt)
```
### Download genomes and annotations
* ENSEMBL mouse 96
```{r}
mouse_mart96 <- useMart("ENSEMBL_MART_ENSEMBL", dataset = "mmusculus_gene_ensembl", 
                   host = "https://apr2019.archive.ensembl.org")
#listAttributes(mouse_mart96)
#listFilters(mouse_mart96)
mouse_ens <- getBM(attributes = c("ensembl_gene_id", "external_gene_name", "gene_biotype"),
      mart = mouse_mart96)
```
# Get background genes
```{r}
full_mouse_genes <- mouse_ens %>%
  clean_names() %>%
  pull(ensembl_gene_id)
```
# Load the summary table
```{r}
summary_table <- read_csv("./Glial-summary-table.csv")
all_protrusion <- filter(summary_table, RNA_in_protrusion == "12")
all_enriched <- filter(summary_table, enriched_in_protrusion == "4"|enriched_in_protrusion == "3")
all_translated <- filter(summary_table, translation_in_protrusion == "4")
protrusion_enriched <- filter(summary_table, RNA_in_protrusion == "12" & enriched_in_protrusion == "4"|enriched_in_protrusion == "3")
protrusion_translated <- filter(summary_table, RNA_in_protrusion == "12" & translation_in_protrusion == "4")
protrusion_enriched_translated <- filter(summary_table, RNA_in_protrusion == "12" & translation_in_protrusion == "4" & enriched_in_protrusion == "3"|enriched_in_protrusion == "4")
```
# Perform TopGO
```{r}
## Custom function
source("./runTopGO.R")

runTopGO_dalia <- function(ontology, target_list){
  runTopGO(ontology = ontology,
           species = "mouse",
           backgroundGenes = full_mouse_genes,
           targetedGenes = target_list) %>%
    mutate(Ontology = ontology)
}
```
## Define ontologies
```{r}
ontologies <- c("BP", "MF", "CC")
```
## Perform TopGO
```{r}
all_protrusion_onto <- map2_dfr(ontologies, list(all_protrusion$gene_id), runTopGO_dalia)
all_enriched_onto <- map2_dfr(ontologies, list(all_enriched$gene_id), runTopGO_dalia)
all_translated_onto <- map2_dfr(ontologies, list(all_translated$gene_id), runTopGO_dalia)
protrusion_enriched_onto <- map2_dfr(ontologies, list(protrusion_enriched$gene_id), runTopGO_dalia)
protrusion_translated_onto <- map2_dfr(ontologies, list(protrusion_translated$gene_id), runTopGO_dalia)
protrusion_enriched_translated_onto <- map2_dfr(ontologies, list(protrusion_enriched_translated$gene_id), runTopGO_dalia)
```
## Export
```{r}
write_csv(all_protrusion_onto, "./output/all_protrusion_onto_14042022.csv")
write_csv(all_enriched_onto, "./output/all_enriched_onto_14042022.csv")
write_csv(all_translated_onto, "./output/all_translated_onto_14042022.csv")
write_csv(protrusion_enriched_onto, "./output/protrusion_enriched_onto_14042022.csv")
write_csv(protrusion_translated_onto, "./output/protrusion_translated_onto_14042022.csv")
write_csv(protrusion_enriched_translated_onto, "./output/protrusion_enriched_translated_onto_14042022.csv")
```